code refactoring and picking hardcore values from config
project-sunbird/sunbird-bot pull request #13
Opened 2020-09-28 10:05 UTC by ajinkyaghodake123

2020-09-28 10:15 UTC, waibhavchandra approved these changes

2020-09-29 05:21 UTC, mathewjpallan requested changes

2020-09-30 05:40 UTC, ajinkyaghodake123 commented on router/appRest.js
> +					sendChannelResponse(res, chatflowConfig['step1']['messageKey'], data.channel, data.recipient);
done

2020-09-30 05:40 UTC, ajinkyaghodake123 commented on router/appRest.js
> +					menuDrivenLogic(data, res, data.channel, chatflowConfig, data.recipient)
done

2020-09-30 05:46 UTC, ajinkyaghodake123 commented on router/config/config.js
> +config.WHATSAPP_AUTHORIZATION      = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuZXRjb3Jlc2FsZXNleHAiLCJleHAiOjI0MjUxMDI1MjZ9.ljC4Tvgz031i6DsKr2ILgCJsc9C_hxdo2Kw8iZp9tsVcCaKbIOXaFoXmpU7Y
DONE

2020-09-30 05:53 UTC, ajinkyaghodake123 commented on router/appRest.js
> +		if (channel == config.WHATSAPP){
@mathewjpallan Keeping the subtype channel specific will  any problem in further queries?

2020-09-30 17:04 UTC, mathewjpallan approved these changes

2020-09-30 17:05 UTC, merged