Issue #SB-23764 fix: Remove the first message on chatbot
project-sunbird/sunbird-bot pull request #59
Opened 2021-04-09 07:32 UTC by Nik720

2021-04-09 07:47 UTC, vinukumar-vs requested changes

2021-04-09 07:47 UTC, vinukumar-vs commented on router/appRest.js
> +			freeflowRes = _.cloneDeep(literals.message[freeflowRes.data.menu_key]);
What will happen when menu_key doesn't have data?

2021-04-09 07:47 UTC, vinukumar-vs commented on router/appRest.js
> + * @description This method is use to decide message for web & whatsapp bot based on menu_key
Good.. :)

2021-04-09 09:39 UTC, Nik720 commented on router/appRest.js
> +			freeflowRes = _.cloneDeep(literals.message[freeflowRes.data.menu_key]);
If the menu key doesn't have data then it will return the same data that we got from Rasa

2021-04-14 07:49 UTC, vinukumar-vs approved these changes

2021-04-14 07:50 UTC, merged